# Generated by Django 5.1.2 on 2024-10-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marker_id', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('marked', 'Marked'), ('missing', 'Missing'), ('candidate', 'Candidate'), ('other', 'Other')], max_length=10)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocks', to='rocks.lake')),
            ],
        ),
    ]
